name: Free Manual Updater

on:
  issue_comment:
    types: [created]

jobs:
  manual_update:
    # 仅当评论内容包含精确的触发词 "/update_page" 时运行
    if: contains(github.event.comment.body, '/update_page')
    runs-on: ubuntu-latest
    
    # 权限配置 (允许 Action 写入和提交更改)
    permissions:
      contents: write
      issues: write

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 3. Execute Manual Update Script
        id: manual_execute
        env:
          # 传递用户评论内容给 Python 脚本
          USER_COMMENT: ${{ github.event.comment.body }}
        run: python scripts/manual_update.py
        
      - name: 4. Commit Changes
        # 这一步将由脚本修改过的文件提交回仓库
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'AUTO: Update content via GitHub Issue comment'